# Generated by Django 4.2.6 on 2023-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Noti_Comment",
        ),
        migrations.RemoveField(
            model_name="noti_study",
            name="comments",
        ),
        migrations.AddField(
            model_name="notifications",
            name="is_check",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Noti_Story",
        ),
        migrations.DeleteModel(
            name="Noti_Study",
        ),
    ]
