# Generated by Django 4.2.6 on 2023-11-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("study", "0001_initial"),
        ("alrarm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="study.study",
            ),
        ),
    ]
