# Generated by Django 4.2.6 on 2023-11-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("alrarm", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="User",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="user.userprofile",
            ),
        ),
    ]
