# Generated by Django 4.2.6 on 2023-11-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alarm", "0001_initial"),
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="story.post",
            ),
        ),
    ]
