# Generated by Django 4.2.6 on 2023-10-24 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_author', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='study',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='study_likes', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='study',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='study_participants', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='study',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='study_stacks', to='study.stack'),
        ),
    ]
