# Generated by Django 4.2.6 on 2023-10-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_study_author_alter_study_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='study',
        ),
    ]
