# Generated by Django 4.2.6 on 2023-10-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('study', '0003_remove_stack_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='study_likes', to='user.userprofile'),
        ),
    ]
