# Generated by Django 4.2.6 on 2023-10-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_study_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='participant_count',
            field=models.CharField(choices=[('undefined', '인원 미정'), ('2', '2명'), ('3', '3명'), ('4', '4명'), ('5', '5명'), ('6', '6명'), ('7', '7명'), ('8', '8명'), ('9', '9명'), ('10', '10명이상')], default='undefined', max_length=10),
        ),
    ]
